### ISSUE TITLE
goog.events.KeyCodes gets mangled under advanced optimizations

### ISSUE THREAD

**Issue by darwin** [spellhouse/phalanges#4]
This how `goog.events.KeyCodes` looks in my project when compiled with :advanced optimizations:https://gist.github.com/darwin/b6586cc33f42dcfe6f83

This breaks `keyword->keycode` which operates on magled key names:
https://github.com/spellhouse/phalanges/blob/8832b00a7edf41aa653f95876a44109577daed48/src/phalanges/core.cljs#L34-L52

I would suggest defining phalanges own replacement for goog.events.KeyCodes as ClojureScript map. ClojureScript  compiler should then ensure correct behaviour in all compilation modes.

**Comment by noprompt** [comment]
@darwin Hey thanks for catching this. Would you be willing to make the patch? I can't get to it right now.

**Comment by darwin** [comment]
Ah. 1.0.5 is busted :-( keywod->keycode is missing closing brace. I wonder why it worked for me on my local machine. I did `lein cljsbuild once` and `lein install` and all was fine. I was able to include it in my local project.
